outDir = "site/built/data"

[modules.HyperOOP]
path = "node_modules/hyperoop/dist"
package = "node_modules/hyperoop/package.json"
exclude = ["proxperty"]

[modules.Router]
path = "node_modules/hyperoop-router/dist"
package = "node_modules/hyperoop-router/package.json"
exclude = ["index"]

[modules.RedoUndo]
path = "node_modules/redoundo/dist"
package = "node_modules/redoundo/package.json"
exclude = []
